name: fluttercomponenets
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  
  # Use these specific versions known to work without the PigeonUserDetails error
  firebase_core: ^2.26.0  # Downgrade from ^3.x.x
  firebase_auth: ^4.17.7  # Downgrade from ^5.x.x
  cloud_firestore: ^4.8.0  # Adjust version to match core/auth
  firebase_storage: ^11.7.0  # If you're using Firebase Storage
  google_sign_in: ^6.1.4  # If you're using Google Sign-In
  
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo.png
