name: fluttercomponenets
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  firebase_auth: ^5.3.1
  provider: ^6.1.2
  http: ^1.1.0
  url_launcher: ^6.2.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  fl_chart: ^0.66.0
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo.png
