name: tasksync
description: "TaskSync - A comprehensive project management application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.0
  
  # Updated Firebase plugins for better Windows compatibility
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  google_sign_in: ^6.2.1
  
  # State management and navigation
  flutter_bloc: ^8.1.6
  go_router: ^14.3.0
  
  # Storage and preferences
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  
  # UI and animations
  animations: ^2.0.11
  flutter_staggered_animations: ^1.1.1
  
  # Date handling
  table_calendar: ^3.1.2
  
  # Image handling
  image_picker: ^1.1.2
  
  # HTTP requests
  http: ^1.2.2
  
  # Utils
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
